version: "3"
services:
  node:
    container_name: node
    image: iamjagr68/tinyurl-microservice:v0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HOST=localhost
      - PORT=8080
      - LOG_DIR=logs
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASS=
      - MONGO_DB=izea
      - HASH_SALT=izea rocks
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
